package org.acme;

public record Car(String id, String brand, String model, int year) {
    // This is a simple record class representing a car
    // It has three fields: make, model, and year
    // The constructor and getters are automatically generated by the record keyword


}
